language: node_js

node_js:
  - "5.1"

deploy:
  provider: openshift
  user: "dementorvinegar@gmail.com"
  password: "041291" # can be encrypted
  domain: "enliteapp"
  app: dev
  deployment_branch: master

after_success:
  - git config --global user.email "travis@localhost.localdomain"
  - git config --global user.name "Travis CI"
  - git add .dpl/
  - git commit -am "Travis change"
