language: node_js

node_js:
  - "6.9.0"

deploy:
  provider: openshift
  user: "enlitedmind@gmail.com"
  password: "enliteopenshift" # can be encrypted
  domain: "enlited"
  app: prod
  deployment_branch: master
  skip_cleanup: true
